### ISSUE TITLE
Unable to test because of Solar issue

### ISSUE THREAD

**Issue by denuoweb** [qtumproject/qtum-ipfs#1]
3: Install Solar. Solar is a smart contract deployment tool of Qtum.

go get -u github.com/qtumproject/solar/cli/solar

GIVES ME THIS ERROR

package github.com/ethereum/go-ethereum/crypto/sha3: cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
/usr/lib/go-1.6/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
/home/mobileapi/gocode/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)
package context: unrecognized import path "context" (import path does not begin with hostname)

**Comment by aitianxiang** [comment]
this error has been fixed.try again please.
